---
# ----------------------------------------------------------------------------
# tasks file for ntp
# ----------------------------------------------------------------------------

- name: get current timezone
  shell: timedatectl | grep 'Time zone' | awk '{ print $3 }'
  register: timezone
  changed_when: False

- debug: msg="timezone info {{ timezone.stdout }}"

- name: ensure timezone is correct
  command: timedatectl set-timezone {{ ntp_timezone }}
  when: timezone.stdout != "{{ ntp_timezone }}"

- name: ensure ntp is installed
  yum: name=ntp state=latest

- name: deploy ntp configuration
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
            owner=root group=root mode=0644

- name: ensure ntpd is running
  service: name=ntpd.service state=running enabled=yes
