#!/bin/bash
systemctl stop sshd.service
yum makecache
yum install -y epel-release
yum install -y awscli
/usr/bin/easy_install --script-dir /opt/aws/bin https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz
cp -v /usr/lib/python2*/site-packages/aws_cfn_bootstrap*/init/redhat/cfn-hup /etc/init.d
chmod +x /etc/init.d/cfn-hup
groupadd devops --system
echo '%devops ALL=(ALL) NOPASSWD: ALL' | tee --append /etc/sudoers
sudo groupadd euler --system
sudo useradd euler --comment 'Packer created' --system --create-home --gid euler --groups devops --shell /bin/bash
sudo sed -i '/Defaults    requiretty/a Defaults:centos !requiretty' /etc/sudoers
sudo sed -i '/Defaults    requiretty/a Defaults:euler !requiretty' /etc/sudoers
sudo mkdir /home/euler/.ssh -m 0777
sudo chown euler /home/euler/.ssh
aws s3 cp s3://prov-installs/Ansible/eulerpublickey /home/euler/.ssh/authorized_keys
chown euler /home/euler/.ssh/authorized_keys
chmod 0700 /home/euler/.ssh
chmod 0600 /home/euler/.ssh/authorized_keys
systemctl start sshd.service
